version: '3.7'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: es1
    environment:
      - node.name=es1
      - cluster.name=standalone
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
