# docker-compose-kibana.yml

version: '3.7'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es-singlenode:9200
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
