# docker-compose-cluster.yml

version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=my_cluster
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data1:/usr/share/elasticsearch/data
      - ./config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./logs1:/usr/share/elasticsearch/logs
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=my_cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - ./data2:/usr/share/elasticsearch/data
      - ./config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./logs2:/usr/share/elasticsearch/logs
    networks:
      - esnet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=my_cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9200
      - 9302:9300
    volumes:
      - ./data3:/usr/share/elasticsearch/data
      - ./config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./logs3:/usr/share/elasticsearch/logs
    networks:
      - esnet

volumes:
  data1:
  data2:
  data3:
  logs1:
  logs2:
  logs3:

networks:
  esnet:
